<a href="https://colab.research.google.com/github/Yevhenii-Taran-9/Machine-Learning/blob/main/%D0%A2%D0%B0%D1%80%D0%B0%D0%BD_%D0%BF%D1%80_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.__version__

'2.0.2'

1. Створіть одновимірний масив (вектор) зі значеннями квадратних коренів з кожного
натурального числа, починаючи з 1, та виведіть його значення.

In [ ]:
vector = np.sqrt(np.arange(1, 11))

vector

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями
коренів 4 ступеня перших дійсних чисел

In [ ]:
matrix = np.sqrt(np.sqrt(np.arange(1, 10).reshape(3,3)))

matrix

array([[1.        , 1.18920712, 1.31607401],
       [1.41421356, 1.49534878, 1.56508458],
       [1.62657656, 1.68179283, 1.73205081]])

3. Створіть масив розміром 3x3, заповніть його випадковими натуральними числами від
1 до 50 та знайдіть суму елементів кожного рядка.

In [ ]:
matrix = np.random.randint(1, 51, (3,3))

row_sums = matrix.sum(axis=1)

row_sums

array([71, 72, 53])

4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами від -0.9
до 0.9 та виведіть його значення.

In [ ]:
matrix = np.random.uniform(-0.9, 0.9, (4,4))

matrix

array([[-0.17606808,  0.80151671, -0.48393148,  0.77887309],
       [ 0.3847473 ,  0.60428843,  0.24454055, -0.23891202],
       [-0.83877114,  0.35617758, -0.80468684,  0.56598362],
       [-0.72318499,  0.61152635,  0.89959487, -0.59901864]])

5. Створіть два одновимірних масиви розміром 7, заповніть їх випадковими цілими
числами в діапазоні від 1 до 5 та виконайте на них поелементні операції додавання,
віднімання та множення.

In [ ]:
a = np.random.randint(1, 6, 7)
b = np.random.randint(1, 6, 7)

add = a + b
sub = a - b
mul = a * b

add, sub, mul

(array([4, 2, 4, 4, 4, 1, 2]),
 array([4, 1, 1, 2, 3, 4, 1]),
 array([8, 3, 5, 6, 7, 5, 3]),
 array([ 0,  1,  3,  2,  1, -3,  1]),
 array([16,  2,  4,  8, 12,  4,  2]))

6. Створіть дві матриці 3x3, заповніть їх довільними цілими числами від 0 до 5 та
знайдіть їх добуток.

In [ ]:
A = np.random.randint(0, 6, (3,3))
B = np.random.randint(0, 6, (3,3))

product = A @ B
product

array([[19, 20,  5],
       [36, 33, 25],
       [39, 39, 15]])

7. Створіть дві матриці розміром 2x3 та 3x4, заповніть їх випадковими цілими числами
в діапазоні від 1 до 7 та перемножте їх між собою.

In [ ]:
A = np.random.randint(1, 8, (2,3))
B = np.random.randint(1, 8, (3,4))

product = A @ B
product

array([[18, 26, 17, 11],
       [30, 34, 34, 15]])

8. Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні
від 1 до 15 та знайдіть її обернену матрицю.

In [ ]:
matrix = np.random.randint(1, 16, (2,2))
inverse = np.linalg.inv(matrix)

inverse

array([[-1.66666667,  0.66666667],
       [ 1.33333333, -0.33333333]])

9. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні
від 3 до 15 та транспонуйте її.


In [ ]:
matrix = np.random.randint(3, 16, (3,3))
transposed = matrix.T

transposed

array([[ 5, 11,  9],
       [13,  4, 11],
       [14,  6,  3]])

10. Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю
випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими цілими
числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.


In [ ]:
matrix = np.random.randint(1, 11, (3,4))
vector = np.random.randint(1, 11, (4,1))
product = matrix @ vector

product

array([[116],
       [126],
       [ 29]])

11. Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю
випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами
від 0 до 1, і знайдіть добуток матриці на вектор.


In [ ]:
matrix = np.random.rand(2,3)
vector = np.random.rand(3,1)
product = matrix @ vector

product

array([[1.16734631],
       [0.57830701]])

12. Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в
діапазоні від 1 до 5 та знайдіть добуток всіх елементів першої матриці.

In [ ]:
A = np.random.randint(1, 6, (3,3))
product = A.prod()

product

np.int64(7200)

13. Створіть дві матриці розміром 3x3, заповніть їх випадковими дійсними числами в
діапазоні від -1 до 1 та знайдіть різницю їх елементів.


In [ ]:
A = np.random.uniform(-1, 1, (3,3))
B = np.random.uniform(-1, 1, (3,3))
difference = A - B

difference

array([[ 1.1275434 ,  0.95003246,  0.66736545],
       [-0.79864637,  1.37676942, -0.95007499],
       [-0.66839698, -0.69028454, -0.17521902]])

14. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в
діапазоні від -3 до 3 та знайдіть суму елементів на головній діагоналі.

In [ ]:
matrix = np.random.uniform(-3, 3, (3,3))
diag_sum = np.trace(matrix)

diag_sum

np.float64(-0.24064469113380493)

15. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в
діапазоні від -0.5 до 0.5 та знайдіть вектор-стовпчик, що містить суму елементів
кожного стовпця матриці.

In [ ]:
matrix = np.random.uniform(-0.5, 0.5, (3,3))
col_sums = matrix.sum(axis=0).reshape(-1,1)

col_sums

array([[0.37494523],
       [0.64532344],
       [0.36166652]])